---
alpha:
  enabled: true
  version:
    template: "{{version}}-alpha"
  requirements:
    tests: []
  release:
    manual: true
    waitForTracks: []
    platforms:
      - ios
      - web
    allowedUsers:
      - lucasilverentand
beta:
  enabled: true
  version:
    template: "{{version}}-beta"
  requirements:
    tests: []
  release:
    manual: true
    waitForTracks: []
    platforms:
      - ios
      - web
    allowedUsers:
      - lucasilverentand
live:
  enabled: true
  version:
    template: "{{version}}"
  requirements:
    tests: []
  release:
    manual: true
    waitForTracks: []
    platforms:
      - ios
      - web
    allowedUsers:
      - lucasilverentand
