name: Create Release Tracking Issue

on:
  push:
    branches:
      - main

jobs:
  create:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: .

      - name: Create Issue
        uses: onezerocompany/coding/actions/release-issues@main
        with:
          # read the release.json file and pass it as an input to the action
          settings: "$(cat release.json)"
